sudo: false
language: java
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8

jobs:
  include:
    - script: mvn test -Droot-level="WARN"
      after_success:
        - mvn jacoco:report-aggregate coveralls:report
        - bash <(curl -s https://codecov.io/bash) 

    - stage: GitHub Release
      if: tag IS present
      jdk: openjdk11
      script: mvn package -Dmaven.test.skip=true
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file_glob: true
        file:
          - gui/target/similarImage*.jar
          - cli/target/similarImage*.jar
        on:
          tags: true
