sudo: false
language: java

jobs:
  include:
    - script: mvn test -Droot-level="WARN"
      after_success:
        - mvn jacoco:report-aggregate coveralls:report
        - bash <(curl -s https://codecov.io/bash) 
      jdk: oraclejdk8
    - stage: GitHub Release
      if: tag IS present
      jdk: oraclejdk8
      script: mvn package -Dmaven.test.skip=true
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file_glob: true
        file:
          - gui/target/similarImage*.jar
          - cli/target/similarImage*.jar
        on:
          tags: true
